[project]
authors = ["timoverlaan <t.verlaan@tudelft.nl>"]
channels = ["conda-forge"]
description = "Reproducible environment for processing the ROSMAP dataset"
name = "rosmap-processing"
platforms = ["win-64", "linux-64"]
version = "0.1.1"

[system-requirements]
linux = "3.10"  # Lower for older kernel on DAIC
# cuda = "12.4"  # (not necessary for processing)

[tasks]

[dependencies]
ipykernel = "*"
psutil = ">=5.9.8,<5.10.dev0"
pandas = ">=2.2.3,<3"

r-base = ">=4.2"
r-seurat = "*"
r-hdf5r = "*"
r-reticulate = "*"
r-remotes = "*"

[pypi-dependencies]
synapseclient = ">=4.7.0"
